//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_nong_san
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONDATs = new HashSet<CHITIETDONDAT>();
        }
    
        public int MADH { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<long> TONGTIEN { get; set; }
        public Nullable<int> MATK { get; set; }
        public Nullable<long> DIEMSUDUNG { get; set; }
        public Nullable<long> DIEMTICH { get; set; }
        public Nullable<int> HINHTHUCTHANHTOAN { get; set; }
        public string DIACHINHANHANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDAT> CHITIETDONDATs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
