//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_nong_san
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONDATs = new HashSet<CHITIETDONDAT>();
            this.CHITIETGIOHANGs = new HashSet<CHITIETGIOHANG>();
        }         
        public int MASP { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mã Code.")]
        public string MACODE { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Tên sản phẩm.")]
        public string TENSP { get; set; }
        [Required(ErrorMessage = "Vui lòng điền URL.")]
        public string URL { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Giá.")]
        public Nullable<long> GIA { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mã Giảm Giá.")]
        public Nullable<int> MAGIAMGIA { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn hình.")]
        public string HINH { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Số lượng tồn.")]
        public Nullable<int> SOLUONGTON { get; set; }
        [Required(ErrorMessage = "Vui lòng Chọn ngày nhập.")]
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        [Required(ErrorMessage = "Vui lòng lựa chọn bán chạy.")]
        public Nullable<int> BANCHAY { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mô tả ngắn.")]
        public string MOTANGAN { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mô tả.")]
        public string MOTA { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mã Code.")]
        public Nullable<int> ANHIEN { get; set; }
        [Required(ErrorMessage = "Vui lòng lựa chọn bán chạy.")]
        public int MAHSX { get; set; }
        [Required(ErrorMessage = "Vui lòng lựa chọn hãng sản xuất.")]
        public int MALOAI { get; set; }
        [Required(ErrorMessage = "Vui lòng lựa chọn loại sản phẩm.")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDAT> CHITIETDONDATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual GIAMGIA GIAMGIA { get; set; }
        public virtual HANGSANXUAT HANGSANXUAT { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
