//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_nong_san
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        public int MATK { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public Nullable<long> SOTRUYCAP { get; set; }
    }
}
